"""rename address

Revision ID: 00939f02dd6d
Revises: 0e036dd04652
Create Date: 2024-06-29 12:20:59.269794

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '00939f02dd6d'
down_revision = '0e036dd04652'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("departments", "adress", new_column_name="location")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("departments", "location", new_column_name="adress")
    # ### end Alembic commands ###
