"""fixing spelling errors on Department table

Revision ID: 0e036dd04652
Revises: 63402e24d281
Create Date: 2024-06-29 12:15:59.210768

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0e036dd04652'
down_revision = '63402e24d281'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table("department", "departments")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table("department", "departments")
    # ### end Alembic commands ###
