"""adding department table

Revision ID: 63402e24d281
Revises: efe2fe38d3d0
Create Date: 2024-06-29 12:08:53.580514

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '63402e24d281'
down_revision = 'efe2fe38d3d0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('department',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('adress', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('department')
    # ### end Alembic commands ###
